routes/auth_routes.py
from model.User import User
from flask import (
	Blueprint,
	request,
	redirect,
	url_for,
	render_template,
	session,
)
from utils import generate_token

auth_routes = Blueprint("auth", __name__)


@auth_routes.route("/login", methods=["GET", "POST"])
def login():
	if request.method == "GET":
		return login_get()
	else:
		return login_post()


def login_get():
	token = generate_token()
	return render_template("login.html", token=token, messages="")


def login_post():
	form = request.form
	u = User.validate_login(form)
	if u:
		session["user_id"] = u.id
		session.permanent = True
		return redirect(url_for("topic.index"))
	else:
		token = generate_token()
		return render_template("login.html", token=token, messages="用户名或密码错误")


@auth_routes.route("/register", methods=["GET", "POST"])
def register():
	if request.method == "GET":
		return register_get()
	else:
		return register_post()


def register_get():
	token = generate_token()
	return render_template("register.html", token=token, messages="")


def register_post():
	form = request.form
	is_success, messages = User.register(form)
	if is_success:
		return redirect(url_for(".login"))
	else:
		token = generate_token()
		return render_template("register.html", token=token, messages=messages)

routes/profile_routes.py
from flask import (
	Blueprint,
	render_template,
	redirect,
	url_for,
	request,
)
from model.User import current_user
from model.User import User

profile_routes = Blueprint("profile", __name__)

@profile_routes.route("/<int:user_id>")
def profile(user_id):
	cur_user = current_user()
	view_user = User.find_by_id(user_id)
	return render_template("profile/profile.html", current_user=cur_user, view_user=view_user)


@profile_routes.route("/edit", methods=["GET", "POST"])
def edit():
	user = current_user()
	if not user:
		return redirect(url_for("auth.login"))
	if request.method == "GET":
		return render_template("profile/edit_profile.html", user=user)
	else:
		form = request.form
		for k, v in form.items():
			setattr(user, k, v)
		user.update()
		return redirect("/profile/{}".format(user.id))

templates/profile/edit_profile.html
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="/static/css/basic.css">
	<link rel="stylesheet" href="/static/css/style.css">
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.css" rel="stylesheet">
	<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
	<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<style>
		body {
			background-color: RGB(241, 241, 241);
		}
		.container {
			width: 50%;
			margin: 100px auto;
			padding: 100px 100px;
			background-color: white;
			border-radius: 5px;
			box-shadow: 8px 8px 4px RGB(221, 221, 221);
		}
		.btn-success {
			margin-right: 70px;
		}
	</style>
</head>
<body>
    <div id="Top">
        <div class="content">
            <div style="padding-top: 6px;">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>
                    <td width="110" align="left"><a href="/" name="top" title="way to explore"><div id="Logo"></div></a></td>
                    <td width="570" align="right" style="padding-top: 2px;">
						<a href="/topic/" class="top">首页</a>&nbsp;&nbsp;&nbsp;
						{% if not user %}
							<a href="{{ url_for('auth.register') }}" class="top">注册</a>&nbsp;&nbsp;&nbsp;
							<a href="{{ url_for('auth.login') }}" class="top">登录</a>
						{% else %}
							<a href="{{ url_for('profile.edit') }}" class="top">你好，{{user.username}}</a>
						{% endif %}
					</td>
                </tr>
            </table>
            </div>
        </div>
    </div>
	<div class="container">
		<form action="{{ url_for('profile.edit') }}" method="POST" enctype="multipart/form-data">
		  <div class="form-group">
			<label for="username" class="control-label">用户名</label>
			<input type="text" class="form-control" id="username" name="username" placeholder="请输入用户名">
		  </div>
		  <div class="form-group">
			<label for="sex" class="control-label">性别</label>
			<select id="sex" name="sex" class="form-control">
				<option value="男">男</option>
				<option value="女">女</option>
			</select>
		  </div>
		  <div class="form-group">
			<label for="image" class="control-label">头像</label>
			<input type="file" class="form-control" id="image" name="image">
		  </div>
		  <div class="form-group">
			<label for="email" class="control-label">邮箱</label>
			<input type="email" class="form-control" id="email" name="email" placeholder="请输入邮箱">
		  </div>
		  <div class="form-group">
			<label for="description" class="control-label">用户简介</label>
			<textarea id="description" name="description" class="form-control"></textarea>
		  </div>
		  <div class="form-group">
			  <button type="submit" class="btn btn-success">提交</button>
		  </div>
		</form>
	</div>
</body>
</html>

templates/profile/profile.html
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="/static/css/basic.css">
	<link rel="stylesheet" href="/static/css/style.css">
	<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.css" rel="stylesheet">
</head>
<body>
    <div id="Top">
        <div class="content">
            <div style="padding-top: 6px;">
            <table cellpadding="0" cellspacing="0" border="0" width="100%">
                <tr>
                    <td width="110" align="left"><a href="/" name="top" title="way to explore"><div id="Logo"></div></a></td>
                    <td width="570" align="right" style="padding-top: 2px;">
						<a href="/topic/" class="top">首页</a>&nbsp;&nbsp;&nbsp;
						{% if not current_user %}
							<a href="{{ url_for('auth.register') }}" class="top">注册</a>&nbsp;&nbsp;&nbsp;
							<a href="{{ url_for('auth.login') }}" class="top">登录</a>
						{% else %}
							<a href="{{ url_for('profile.edit') }}" class="top">你好，{{current_user.username}}</a>
						{% endif %}
					</td>
                </tr>
            </table>
            </div>
        </div>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-sm-3">
				<img src="{{ view_user.image }}">
			</div>
			<div class="col-sm-9">
				<h1>{{ view_user.username }}</h1>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-3">
				<h3>性别</h3>
			</div>
			<div class="col-sm-9">
				{% if view_user.sex %}
					<p>{{view_user.sex}}</p>
				{% else %}
					<p>未设置</p>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col-sm-3">
				<h3>邮箱</h3>
			</div>
			<div class="col-sm-9">
				{% if view_user.email %}
					<p>{{view_user.email}}</p>
				{% else %}
					<p>未设置</p>
				{% endif %}
			</div>
		</div>
		<div class="row">
			<div class="col-sm-3">
				<h3>个人简介</h3>
			</div>
			<div class="col-sm-9">
				{% if view_user.description %}
					<p>{{view_user.description}}</p>
				{% else %}
					<p>未设置</p>
				{% endif %}
			</div>
		</div>
	</div>
</body>
</html>