routes/auth_routes.py
from model.User import User
from flask import (
	Blueprint,
	request,
	redirect,
	url_for,
	render_template,
	session,
)
from utils import generate_token

auth_routes = Blueprint("auth", __name__)


@auth_routes.route("/login", methods=["GET", "POST"])
def login():
	if request.method == "GET":
		return login_get()
	else:
		return login_post()


def login_get():
	token = generate_token()
	return render_template("login.html", token=token, messages="")


def login_post():
	form = request.form
	u = User.validate_login(form)
	if u:
		session["user_id"] = u.id
		session.permanent = True
		return redirect(url_for("topic.index"))
	else:
		token = generate_token()
		return render_template("login.html", token=token, messages="用户名或密码错误")


@auth_routes.route("/register", methods=["GET", "POST"])
def register():
	if request.method == "GET":
		return register_get()
	else:
		return register_post()


def register_get():
	token = generate_token()
	return render_template("register.html", token=token, messages="")


def register_post():
	form = request.form
	is_success, messages = User.register(form)
	if is_success:
		return redirect(url_for(".login"))
	else:
		token = generate_token()
		return render_template("register.html", token=token, messages=messages)

templates/components/navbar.html
<nav class="clearfix">
    <div class="logo">
        <img src="../../static/logo.png" width="80" height="30">
    </div>
    <div class="menu-wrapper">
        <div class="nav-item">
            <a href="{{ url_for('topic.index') }}">首页</a>
        </div>
        {% if user %}
            <div class="nav-item">
                您好,{{ user.username }}
            </div>
        {% else %}
            <div class="nav-item">
                <a href="{{ url_for('auth.login') }}">登录</a>
            </div>
            <div class="nav-item">
                <a href="{{ url_for('auth.register') }}">注册</a>
            </div>
        {% endif %}
    </div>
</nav>