routes/board_routes.py
from flask import (
	Blueprint,
	render_template,
	request,
	redirect,
	url_for,
)
from model.User import current_user
from model.Board import Board

board_routes = Blueprint("board", __name__)

@board_routes.route("/add", methods=["GET", "POST"])
def add():
	u = current_user()
	if not u:
		return redirect(url_for("topic.index"))
	if request.method == "GET":
		return render_template("board/add_board.html")
	else:
		Board.new_and_save(request.form)
	return redirect(url_for("topic.index"))

routes/topic_routes.py
from flask import (
	Blueprint,
	render_template,
	request,
	redirect,
	url_for,
)
from model.Topic import Topic
from model.User import current_user
from model.Reply import Reply
from model.Board import Board

topic_routes = Blueprint("topic", __name__)


@topic_routes.route("/")
def index():
	board_id = request.args.get("board", None)
	if board_id:
		board_id = int(board_id)
	topics = get_topics(board_id)
	boards = Board.all()
	user = current_user()
	return render_template("topic/index.html",
						   user=user,
						   topics=topics,
						   board_id=board_id,
						   boards=boards)


@topic_routes.route("/add", methods=["GET", "POST"])
def add():
	u = current_user()
	if not u:
		return redirect(url_for("auth.login"))
	if request.method == "GET":
		boards = Board.all()
		return render_template("topic/add.html", user_id=u.id, boards=boards)
	Topic.new_and_save(request.form)
	return redirect(url_for(".index"))


@topic_routes.route("/t/<int:topic_id>")
def detail(topic_id):
	t = Topic.find_by_id(topic_id)
	u = current_user()
	rs = Reply.find_by(topic_id=topic_id)
	update_views(t)
	rs.sort(key=lambda x: x.floor)
	floor_count = len(rs) + 1
	return render_template("topic/detail.html",
						   topic=t,
						   user=u,
						   replies=rs,
						   floor_count=floor_count)


def update_views(topic):
	topic.views += 1
	topic.update()


def get_topics(board_id):
	if not board_id:
		return Topic.all()
	else:
		return [t for t in Topic.all() if t.board_id == int(board_id)]

templates/topic/add.html
<html>
	<head>
		<meta charset="utf-8">
		<link href="https://cdn.bootcss.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet">
		<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
		<script src="https://cdn.bootcss.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
        <link rel="stylesheet" href="/static/css/style.css">
        <link rel="stylesheet" href="/static/css/fonts.css">
		<style>
			body {
				background-color: RGB(241, 241, 241);
			}
			.container {
				width: 70%;
				margin: 50px auto;
				padding: 50px 50px;
				background-color: white;
				border-radius: 5px;
				box-shadow: 8px 8px 4px RGB(221, 221, 221);
			}
			.submit-pane {
				margin-top: 10px;
			}
			pre {
				padding: 10px;
				background-color: RGB(231, 231, 231);
			}
		</style>
	</head>
	<body>
		<div class="container">
			<form action="{{ url_for("topic.add") }}" method="POST">
			  <input type="hidden" name="user_id" value={{user_id}}>
			  <div class="form-group">
				<span class="icon-quill"></span>
				<label for="title" class="control-label">文章标题</label>
				<input type="text" class="form-control" id="title" name="title" placeholder="请输入标题">
			  </div>
			  <div class="form-group">
				<span class="icon-book"></span>
				<label for="board" class="control-label">文章主题</label>
				<select id="board" name="board_id" class="form-control">
                    {% for b in boards %}
                        <option value="{{ b.id }}">{{ b.title }}</option>
                    {% endfor %}
				</select>
			  </div>
			  <div class="editor-container">
				  <textarea class="form-control" id="editor" name="content" placeholder="该编辑器支持Markdown语法"></textarea>
			  </div>

			  <div class="form-group">
				<div class="submit-pane">
				  <button type="submit" class="btn btn-success">提交</button>
				 </div>
			  </div>
			</form>
		</div>
		<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
		<script type="text/javascript">
			var e = function(sel) {
				return document.querySelector(sel)
			};
			var simplemde = new SimpleMDE({
				element: e("#editor")
			});
		</script>

	</body>
</html>

templates/topic/detail.html
<html>
<head>
	<meta charset="utf-8">
	<link rel="stylesheet" href="/static/css/style.css">
</head>
<body>
	{% include 'components/navbar.html' %}
    <div class="article-content">
		<h1 class="title">{{ topic.title }}</h1>
		<div class="info">
			<span><a href="/profile/{{ topic.user_id }}">{{ topic.username }}</a></span>
			<span>{{ topic.views }}次浏览</span>
		</div>
		<div class="article" id="article">
			{{ topic.content | trim}}
		</div>
	</div>
	<div class="comment">
		<div class="hint">
			添加一条新回复
		</div>
		<div class="reply-form">
			<form method="POST" action="/reply/add/{{topic.id}}">
				<div class="text">
					<textarea name="content" maxlength="10000" id="reply_content"></textarea>
				</div>
				<span class="gray">请尽量让自己的回复能够对别人有帮助</span>
				<input type="hidden" value="{{topic.id}}" name="topic_id" />
				<input type="hidden" value="{{user.id}}" name="user_id" />
				<input type="hidden" value="{{floor_count}}" name="floor" />
				<button id="add-reply-btn" type="submit">回复</button>
			</form>
		</div>
		<div class="replies">
            {% for r in replies %}
			<div class="floor-wrapper">
				<div class="avatar">
					<img src="https://cdn.v2ex.com/gravatar/63f64b724a65d37e75b28934e249b45b?s=48&amp;d=retro">
				</div>
				<div class="comment-item">
					<div class="comment-info">
						<span>
							<a href="/profile/{{ r.user_id }}">
								{{r.username}}
							</a>
						</span>
						<span>
							第{{r.floor}}楼
						</span>
						<span>
							<a href="/reply/votes/{{r.id}}">
								♥ {{r.likes}}
							</a>
						</span>
					</div>
					<div class="comment-content">
                        {{ r.content}}
					</div>
				</div>
			</div>
            {% endfor %}
		</div>
    </div>
    <script src="/static/lib/markdown.min.js"></script>
    <script>
        var article = document.getElementById('article');
        var markdownText = article.innerHTML.trim();
        var html = markdown.toHTML(markdownText);
        article.innerHTML = html
    </script>
</body>
</html>

templates/topic/index.html
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" href="../static/css/style.css">
    </head>
    <body>
    	{% include 'components/navbar.html' %}
        <nav class="theme-nav">
            {% if board_id %}
                <a href="{{ url_for('topic.index') }}" class="tab">全部</a>
                {% for b in boards %}
                    {% if b.id == board_id %}
                        <a href="{{ url_for('topic.index') }}?board={{ b.id }}" class="tab active">{{ b.title }}</a>
                    {% else %}
                        <a href="{{ url_for('topic.index') }}?board={{ b.id }}" class="tab">{{ b.title }}</a>
                    {% endif %}
                {% endfor %}
            {% else %}
                <a href="/" class="tab active">全部</a>
                {% for b in boards %}
                    <a href="{{ url_for('topic.index') }}?board={{ b.id }}" class="tab">{{ b.title }}</a>
                {% endfor %}
            {% endif %}
        </nav>
        <div class="content">
			<nav class="user-action-nav">
				<a class="publish-btn" href="{{ url_for('topic.add') }}">发布话题</a>
				<a class="publish-btn" href="{{ url_for('board.add') }}">发布板块</a>
			</nav>
            <ul class="item-list">
                {% for t in topics %}
                <li class="item">
                    <h1 class="title-info">
                        <a href="/topic/t/{{ t.id }}">
                            {{ t.title }}
                        </a>
                    </h1>
                    <div class="topic-info">
                        <a class="info" href="{{ url_for('topic.index') }}?board={{ t.board_id }}">
                            {{ t.board }}
                        </a>
                        <a class="info" href="/profile/{{ t.user_id }}">
                            {{ t.username }}
                        </a>
                        <span class="info">
                            {{ t.calc_time() }}
                        </span>
                        <span class="info">
                            {{ t.views }}次浏览
                        </span>
                    </div>
                    <div class="comment-info">
                        <a href="/topic/t/{{ t.id }}#comments">
                            {{ t.comments }}
                        </a>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </body>
</html>